package:
  name: ovation
  version: 2.1.7

source:
  git_url: https://github.com/physion/ovation-python.git
  git_tag: v2.1.7
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1
  
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ovation = ovation:main
    #
    # Would create an entry point called ovation that calls ovation.main()


requirements:
  build:
    - python

  run:
    - python
    - quantities
    - scipy
    - pandas
    - phyjnius

test:
  # Python imports
  imports:
    - ovation

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://ovation.io
  license: GNU General Public License v3 (GPLv3)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
